import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {

  console.log(data)

  const city = data.map(ev => {
    return (

      <Link key={ev.id} href={`/events/${ev.id}`} passHref>
        <Image
          src={ev.image}
          alt={ev.title}
          width={200}
          height={200}
        />
        <h2>{ev.title}</h2>
        <p>{ev.description}</p>
      </Link>
    )
  })

  return (
    <>
      <Head>
        <title>Events next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <Link passHref href='/'>
            Home
          </Link>
          <Link passHref href='/events'>
            Events
          </Link>
          <Link passHref href='/about-us'>
            About Us
          </Link>
        </nav>
      </header>
      <main className={styles.main}>
        {city}
        <p>ullalala</p>
      </main>
      <footer className={styles.footer}>
        My app in next
      </footer>
    </>
  )
}

export async function getServerSideProps() {

  // const data = await import ('./../../data/data.json');
  const { events_categories } = await import('./../../data/data.json');

  return {
    props: {
      data: events_categories
    }
  }
}
